[project]
name = "root"
version = "0.0.0"
readme = "README.md"


[tool.rye]
managed = true
virtual = true

[tool.rye.workspace]
members = ["packages/*"]

[tool.black]
target-version = ["py312"]
line-length = 120
